# Generated by Django 6.0.1 on 2026-02-02 18:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RAGConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rag_folder_name', models.CharField(default='default', help_text='Name of the folder containing documents to index', max_length=255)),
                ('embedding_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('huggingface', 'HuggingFace (Local)')], default='openai', help_text='Provider for generating embeddings', max_length=20)),
                ('llm_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic')], default='openai', help_text='Provider for LLM generation', max_length=20)),
                ('chunk_size', models.PositiveIntegerField(default=1000, help_text='Target size of each chunk in characters')),
                ('chunk_overlap', models.PositiveIntegerField(default=200, help_text='Number of characters to overlap between chunks')),
                ('top_k', models.PositiveIntegerField(default=5, help_text='Number of relevant chunks to retrieve')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RAG Configuration',
                'verbose_name_plural': 'RAG Configurations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(db_index=True, help_text='UUID for grouping messages into conversations')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], help_text='Role of the message sender', max_length=10)),
                ('content', models.TextField(help_text='The message content')),
                ('context_used', models.JSONField(blank=True, default=list, help_text='List of context chunks used for generating the response')),
                ('sources', models.JSONField(blank=True, default=list, help_text='List of source documents referenced')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='chat_chatme_session_70d41b_idx')],
            },
        ),
    ]
